-- front-end tables
CREATE TABLE checks (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(64) NOT NULL, type VARCHAR(32) NOT NULL, data VARCHAR(512) NOT NULL, fail_count INT NOT NULL DEFAULT 3, success_count INT NOT NULL DEFAULT 2, check_interval INT NOT NULL DEFAULT 60, status ENUM ('online', 'offline') DEFAULT 'online', last_checked TIMESTAMP DEFAULT '2010-01-01 00:00:00', turn_count INT NOT NULL DEFAULT 0, `lock` VARCHAR(16) NOT NULL DEFAULT '', last_locked TIMESTAMP DEFAULT '2010-01-01 00:00:00');
CREATE TABLE contacts (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, type VARCHAR(32) NOT NULL, data VARCHAR(512));
CREATE TABLE alerts (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, check_id INT NOT NULL, contact_id INT NOT NULL);

-- data tables
CREATE TABLE check_results (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, check_id INT NOT NULL, result ENUM ('success', 'fail'), time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
